spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/forum?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    username: 844022972@qq.com
    password: siiqghymdctqbfjg
    host: smtp.qq.com
    default-encoding: UTF-8

server:
  port: 9090
config:
  mail:
    844022972@qq.com